```{r regovertime, cache=cacheon, fig.cap="Årlig registrering i RiksSvikt 2015-2021", fig.width=8, fig.height=7}

tot <- rsdata %>%
  filter(indexyear >= ar - 6 & indexyear <= ar) %>%
  count(indexyear) %>%
  mutate(
    byvar = 5,
    byvarname = "Totalt Index och uppföljningar"
  )

totun <- rsdata %>%
  filter(indexyear >= ar - 6 & indexyear <= ar) %>%
  group_by(PATIENTREFERENCE, indexyear) %>%
  slice(1) %>%
  ungroup() %>%
  count(indexyear) %>%
  mutate(
    byvar = 6,
    byvarname = "Unika patienter"
  )

type <- rsdata %>%
  filter(indexyear >= ar - 6 & indexyear <= ar) %>%
  group_by(indexyear) %>%
  count(ttype) %>%
  mutate(
    byvar = 1:n(),
    byvarname = ttype
  ) %>%
  ungroup() %>%
  select(-ttype)

hfdur <- rsdata %>%
  filter(indexyear >= ar - 6 & indexyear <= ar, ttype == "Index") %>%
  filter(!is.na(hfdur)) %>%
  group_by(indexyear) %>%
  count(hfdur) %>%
  mutate(
    byvar = 1 + (1:n()) / 100,
    byvarname = paste("Index ", hfdur)
  ) %>%
  ungroup() %>%
  select(-hfdur)

all <- bind_rows(tot, totun, type, hfdur) %>%
  pivot_wider(names_from = indexyear, values_from = n) %>%
  arrange(byvar) %>%
  select(-byvar)

plotall <- all %>%
  select(-byvarname) %>%
  t()

cexmy <- 0.75
# c(bottom, left, top, right) default c(5, 4, 4, 2) + 0.1.
par(mar = c(4, 4, 0, 11) + 0.1)

matplot(plotall,
  # type = "b",
  type = "l",
  # pch = 16,
  col = rev(global_colsblue),
  lty = 1,
  lwd = 3,
  # cex = 1.2,
  axes = FALSE,
  xaxs = "i",
  yaxs = "i",
  # xlim = c(ar - 6, ar),
  ylab = "Antal registreringar",
  xlab = labnams[1],
  cex.lab = cexmy,
  ylim = c(0, 18100)
)

axis(2, at = seq(0, 18000, 2000), cex.axis = cexmy, las = 2)

axis(1, at = 1:length((ar - 6):ar), labels = (ar - 6):ar, cex.axis = cexmy)

axis(2,
  at = all %>% pull(!!sym(paste(ar))),
  labels = all %>% pull(byvarname),
  line = -26,
  tick = FALSE, cex.axis = cexmy,
  las = 2,
  hadj = 0,
  gap.axis = -10000000
)
#
# mtext(all[1, "byvarname"], side = 1, line = 2, at = -10, adj = 0, cex = 0.5)
# axis(1, at = 1:length((ar - 6):ar), labels = all[1, paste((ar - 6):ar)], line = 1, tick = FALSE, cex.axis = 0.5)
#
# mtext(all[2, "byvarname"], side = 1, line = 3, at = -10, adj = 0, cex = 0.5)
# axis(1, at = 1:length((ar - 6):ar), labels = all[2, paste((ar - 6):ar)], line = 2, tick = FALSE, cex.axis = 0.5)
#
# mtext(all[3, "byvarname"], side = 1, line = 4, at = -10, adj = 0, cex = 0.5)
# axis(1, at = 1:length((ar - 6):ar), labels = all[3, paste((ar - 6):ar)], line = 3, tick = FALSE, cex.axis = 0.5)
#
# mtext(all[4, "byvarname"], side = 1, line = 5, at = -10, adj = 0, cex = 0.5)
# axis(1, at = 1:length((ar - 6):ar), labels = all[4, paste((ar - 6):ar)], line = 4, tick = FALSE, cex.axis = 0.5)
#
# mtext(all[5, "byvarname"], side = 1, line = 6, at = -10, adj = 0, cex = 0.5)
# axis(1, at = 1:length((ar - 6):ar), labels = all[5, paste((ar - 6):ar)], line = 5, tick = FALSE, cex.axis = 0.5)
#
# mtext(all[6, "byvarname"], side = 1, line = 7, at = -10, adj = 0, cex = 0.5)
# axis(1, at = 1:length((ar - 6):ar), labels = all[6, paste((ar - 6):ar)], line = 6, tick = FALSE, cex.axis = 0.5)
#
# mtext(all[7, "byvarname"], side = 1, line = 8, at = -10, adj = 0, cex = 0.5)
# axis(1, at = 1:length((ar - 6):ar), labels = all[7, paste((ar - 6):ar)], line = 7, tick = FALSE, cex.axis = 0.5)
```

```{r regovertimetab, cache=cacheon}
colnams <- colnames(all)
colnams[1] <- ""
colnames(all) <- colnams
default_kable(all, caption = "Årlig registrering i RiksSvikt 2015-2021")
```
